import type { Resource } from "./types";

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "1",
    url: "https://www.are.na",
    title: "Are.na",
    description: "A platform for connecting ideas and building knowledge collaboratively.",
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    cover_image_override: null,
    category: "tools",
    is_favorite: true,
    notes: "Love the visual bookmarking approach here.",
    tags: ["research", "bookmarking", "visual"],
    created_at: "2024-06-10T10:00:00Z",
    user_id: "user_1",
  },
  {
    id: "2",
    url: "https://fonts.google.com",
    title: "Google Fonts",
    description: "A library of open-source fonts for web and print.",
    cover_image_url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80",
    cover_image_override: null,
    category: "typography",
    is_favorite: false,
    notes: "Reference for pairing Prata with sans serifs.",
    tags: ["fonts", "type", "free"],
    created_at: "2024-06-09T14:30:00Z",
    user_id: "user_1",
  },
  {
    id: "3",
    url: "https://pentagram.com",
    title: "Pentagram",
    description: "The world's largest independent design consultancy.",
    cover_image_url: "https://images.unsplash.com/photo-1634986666676-ec8fd927c23d?w=600&q=80",
    cover_image_override: null,
    category: "branding",
    is_favorite: true,
    notes: "Study their case study presentation format.",
    tags: ["agency", "identity", "portfolio"],
    created_at: "2024-06-08T09:00:00Z",
    user_id: "user_1",
  },
  {
    id: "4",
    url: "https://tympanus.net/codrops",
    title: "Codrops",
    description: "Useful resources and inspiration for creative minds.",
    cover_image_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80",
    cover_image_override: null,
    category: "creative-technology",
    is_favorite: false,
    notes: "Great for WebGL and animation tutorials.",
    tags: ["webgl", "animation", "tutorial"],
    created_at: "2024-06-07T16:00:00Z",
    user_id: "user_1",
  },
  {
    id: "5",
    url: "https://dribbble.com",
    title: "Dribbble",
    description: "Where designers gain inspiration, feedback, community, and jobs.",
    cover_image_url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80",
    cover_image_override: null,
    category: "portfolios",
    is_favorite: false,
    notes: "Useful for visual reference hunting.",
    tags: ["inspiration", "ui", "community"],
    created_at: "2024-06-06T11:00:00Z",
    user_id: "user_1",
  },
  {
    id: "6",
    url: "https://mitpress.mit.edu",
    title: "MIT Press",
    description: "Publisher of books at the intersection of design, technology, and culture.",
    cover_image_url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80",
    cover_image_override: null,
    category: "books",
    is_favorite: true,
    notes: "Keep checking for new design theory titles.",
    tags: ["books", "theory", "culture"],
    created_at: "2024-06-05T08:00:00Z",
    user_id: "user_1",
  },
  {
    id: "7",
    url: "https://www.siteinspire.com",
    title: "Siteinspire",
    description: "A showcase of the finest web and interactive design.",
    cover_image_url: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&q=80",
    cover_image_override: null,
    category: "websites",
    is_favorite: true,
    notes: "Best curated web design gallery.",
    tags: ["webdesign", "gallery", "inspiration"],
    created_at: "2024-06-04T13:00:00Z",
    user_id: "user_1",
  },
  {
    id: "8",
    url: "https://motionographer.com",
    title: "Motionographer",
    description: "Celebrating the art of motion design and visual storytelling.",
    cover_image_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&q=80",
    cover_image_override: null,
    category: "motion",
    is_favorite: false,
    notes: "Track their featured studios section.",
    tags: ["motion", "animation", "studios"],
    created_at: "2024-06-03T10:00:00Z",
    user_id: "user_1",
  },
];
